# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89bc5b51ffce75054f38b03f76bf4d9f5464e815aa5b7e6ee4f296b5d2b243881c2153a290cb6930b9871dd7ec459f2f2b2014d54877ee31af8cdf7841fac1a1

test:
  secret_key_base: fe682e62d8721cfe61ff031187d2179b53b314cd047efc5f191fb9cbdd9d33f8cc03b7a9ef2d664d272b4621161c9a00ed53b3e40872311f011c17f105700fab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
